### ISSUE TITLE
11.3 error

### ISSUE THREAD

**Issue by DiamondStashers** [TiniVi/safehax#19]
Im on 11.3 and ive done everything it says too but I always get the same error when loading safehax it says PM INIT Failed and I don't know why can anyone help

**Comment by TiniVi** [comment]
Did you run udsploit first?

**Comment by Kuruyia** [comment]
Same problem here: http://gbatemp.net/threads/old-3ds-with-10-3-0-28e.467533/#post-7239843

**Comment by fenderjaguarlol** [comment]
Yes, I have this problem, as Arc13 links to my thread

**Comment by TiniVi** [comment]
@Arc13 @fenderjaguarlol The 10.3 issue is discussed here: #18, which I don't have enough info to fix atm (although I have a guess as to why it's happening, please read there).

Please keep this issue on topic, thanks.

**Comment by DiamondStashers** [comment]
I did run udsploit im follow the 3ds guide and I'm stuck at this no hurry to fix and thanks everyone for your constructive comments if I find anything else I will comment

**Comment by TiniVi** [comment]
@DiamondStashers may I ask what firmware, entrypoint, conditions you're running safehax on? (You can also try to run @Arc13's build over at #18 and see if that helps)

**Comment by DiamondStashers** [comment]
I'll try it thanks and I'm on 11.3.0-36E

**Comment by NightDante** [comment]
Hi, I'm on 11.3.0-36E, and safehax didn't work for me. I tried everything. Read a lot of forums, and nothing. I tried Arc13's safehaxes, but it's not working neither. Homebrew and USDploit are working, but Safehax is not. Can someone help me?
