### ISSUE TITLE
INIT FAILED

### ISSUE THREAD

**Issue by Barryill** [TiniVi/safehax#20]
When I launch safehax, 3DS told "PM INIT FAILED". And I tried a lot of times, even reboot. I don't what going on and how figure out. I put all of files in the correct position.

**Comment by saski003** [comment]
me too i have this problem too

**Comment by Masamune3210** [comment]
Have you ever launched the activity log?

**Comment by david-zzj** [comment]
i have the same issue......

**Comment by TiniVi** [comment]
Firmware, entrypoint, revision, etc. Could you share some info to help me grasp the problem? What you ran before safehax, perhaps?

**Comment by david-zzj** [comment]
old3ds，9.7.0-4U，soundhax
in hbc，succeed udsploit，and run safehax
the issue is occurred：PM INIT FAILED

**Comment by TiniVi** [comment]
Try r19

**Comment by david-zzj** [comment]
oh god，r19 worked perfect.

**Comment by TiniVi** [comment]
Yea i expected that. this is a bug i need to look into when i get the time.

**Comment by david-zzj** [comment]
ok，thx

**Comment by PoopyBlues** [comment]
I have the same problem, soundhax and ver.9.5 old3ds, init failed...
What it is r19?

**Comment by nandaaxyz** [comment]
Safehax Revision 19, click "code" tab and click tags, there will be Safehax r19 there.

**Comment by Aloben** [comment]
How do I use r19? do I copy it into the SD card? if so, where? I keep having the same issue PM INIT FAILED.

**Comment by nandaaxyz** [comment]
Open your SD card, delete 'safehax.3ds' in your '3ds' folder. Then, download safehax r19(.3ds extension) and copy it in '3ds' folder.

don't forget to connect your 3ds to wifi when running safehax, because my 3ds always fail without an internet connection.

**Comment by Aloben** [comment]
Thanks a lot, MNaik, will try and I'll let you know.
