### ISSUE TITLE
Crash to Home Menu

### ISSUE THREAD

**Issue by omnicons** [TiniVi/safehax#24]
I'm using r21 on an o3DSXL running 11.3.0-36U
Entrypoint: Soundhax udsploit: Succeeds
Upon running safehax it tells me CTRTransfer not complete, nothing written to NAND, check lower screen for more info and the lower screen said to press "A" to continue, upon pressing A it returns me to the home menu with no other errors.

**Comment by TiniVi** [comment]
That's not a safehax issue. That would be an issue with the payload you're running (dunno if it's Decrypt9/GodMode9 or what).

**Comment by omnicons** [comment]
Thanks, I'm just following the guide so I'll see about figuring it out, not sure what to do at this point would it just be safe to use another payload?

**Comment by TiniVi** [comment]
Either open the same issue on the respective github repo, or ask for help on available forum topics.
