### ISSUE TITLE
PM INIT FAIL on safehax...

### ISSUE THREAD

**Issue by Plink54** [TiniVi/safehax#26]
Hello to all,
I am using Plailect's guide. Have an old 3dsXL on 9.4.0-10E fw.
system is clean no previous hacks or attempts. I did a factory reset before i begin the process.
Have loaded homebrew channel without problems, but when trying safehax i get the PM INIT FAIL error.
Have used various safehax releases (21, 19,18), have tried rebooting the 3ds, have tried with a game and without, have tried with wifi on and off.
Any ideas would be trully appreciated :)
thanks in advance

**Comment by TiniVi** [comment]
#18, #20

**Comment by Plink54** [comment]
tried the safehack on #18 didnt work, either the solution in #20 :/

**Comment by TiniVi** [comment]
Did you run udsploit first

**Comment by Plink54** [comment]
yes i have run udsploit and it was completed without problems. I tried everything i found on "issues" threads,
 the only thing that i can think of is that something is wrong with my sd (using a micro sd with an adaptor and adaptors sometimes act weirdly). I will go buy a new one in the morning and will try again, see how that goes.
thanks a lot for your help TiniVi :D karma points for you

**Comment by TiniVi** [comment]
@Plink54 This does not seem like an SD card issue, If r19 isn't working right on your lower firmware, and you're running udsploit successfully, I'm not quite sure what the issue may be...

**Comment by OwenGames** [comment]
Turn on wireless :D
