### ISSUE TITLE
11.3.0-36E otp.bin

### ISSUE THREAD

**Issue by ekvasir** [TiniVi/safehax#27]
I'm on 11.3.0-36E old3DS following the guid at https://3ds.guide/ when i run safehax r21 and press Select it says Error: otp.bin doesn't exist and can't be dumped. I followed all the steps up to this point and I'm not sure whats going on

Sorry just read everything again had one file in the 3ds folder insted of the root

**Comment by TiniVi** [comment]
#24, #25
