### ISSUE TITLE
PM INIT FAIL pls help

### ISSUE THREAD

**Issue by gasech2** [TiniVi/safehax#28]
Im using the old3ds，11.1.0-34U，soundhax. Yes i already tried: Restart the console, Check files, etc..

**Comment by TiniVi** [comment]
Did you try reading the other issues? #26 #7 #18

**Comment by gasech2** [comment]
yes..

**Comment by TiniVi** [comment]
And nothing that was suggested worked? I can't exactly get any context with just "etc."

**Comment by gasech2** [comment]
Yeah nothing worked. Sorry about the "etc.."

**Comment by spicenaut** [comment]
So for me, the guide didn't mention the free space thing until part 3 and in safehax I didn't understand it was saying this, but for anyone have problems make sure you have plenty of free space on your SD card.

**Comment by salatest** [comment]
Turn ON Wifi, for me fix.
