### ISSUE TITLE
3ds won't turn on, on indicator LED comes on for about a second and goes off again

### ISSUE THREAD

**Issue by davidflynn2585** [TiniVi/safehax#31]
I was following the boot9strap installation guide by 3ds.guide for my n3ds. I followed it as it said; launch udsploit, exit and then launch safehax, i put in the keys that were asked after safehax loaded up(up down a b etc.) and then I clicked a becasue i was prompted, didn't read why which was a bit silly of me and then my 3ds booted off and won't restart again, the on indicator LED flashes on and no response from the screens at all. Can someone help me? Have i bricked my 3ds for good? i wasn't even at the part of the tutorial when you back up your 3ds and taking the battery out doesn't help

**Comment by TiniVi** [comment]
This is not a safehax bug, this the result of your arm9 payload, please request help at the appropriate repo.

**Comment by stenocyb** [comment]
You can solve this issue by downloading the zip from the Luma3DS repository. Just place the boot.firm contained in the zip file into your root of your SD card.
