### ISSUE TITLE
[FEATURE REQUEST] *.firm payload support.

### ISSUE THREAD

**Issue by annson24** [TiniVi/safehax#32]

**Comment by TiniVi** [comment]
Shouldn't be hard, likely only requires a firmload payload on arm9.

**Comment by TiniVi** [comment]
Untested, but if it works I'll update the repo: [safehax.zip](https://github.com/TiniVi/safehax/files/1100215/safehax.zip)

**Comment by annson24** [comment]
Just saw this, will test later.

how should I name the .firm payloads? safehaxpayload.firm?

**Comment by TiniVi** [comment]
Yeah, that will work. All previous names would work as well since it just checks for the magic "FIRM"

**Comment by annson24** [comment]
Just tried it out, worked like a charm with naming the payload as safehaxpayload.firm, tried to rename the payload to boot.firm as well and it also worked. Great work, thanks for the enhancement. Also tested what name of payload would it prioritize between safehaxpayload.firm and boot.firm, seems like safehaxpayload still has the most priority. Lastly, I tried it on a stock 9.2.0 3ds and it worked well, no more errors on lower firmware as suggested on issue #18 #20 

EDIT: It doesn't seem to load luma v7.1 up to 8.1, tried it with luma v7.0.5 and it worked just fine.

**Comment by TiniVi** [comment]
Alright, thanks for the feedback! I'll update the repo asap.

**Comment by TuxSH** [comment]
~~d5709aff90f6ac95b3a5b0cf9c66a7e1f052ecae is incomplete w/r/t the arm9 entrypoint arguments and will not boot any payload except maybe official firmwares.~~

~~Look at how Luma3DS or b9s do it.~~

I did not realize it could lead to bricks back then.

**Comment by TiniVi** [comment]
@TuxSH it's been on my todo list, but not as a priority

**Comment by TiniVi** [comment]
@TuxSH @annson24 You can try [this](https://github.com/TiniVi/safehax/files/1133550/safehax.zip) build. It _should_ set the args properly.

**Comment by annson24** [comment]
Tested it, when using with decrypt9 or gm9, it freezes with what looks like a snowy bottom screen. When used with luma3ds v7.1 & 8.1 however, it just goes into black screen.

This is tested with stock firmware v9.2.0 on an old 3ds.

**Comment by TiniVi** [comment]
Alright, I'll check it out probably within the next few days.

**Comment by annson24** [comment]
Sorry for bumping this but if you need a screen feedback, I'll be glad to provide one. Sorry if I haven't, was kinda busy these past few days.

**Comment by TiniVi** [comment]
Dropping support, review #34
