### ISSUE TITLE
It doesn´t work help please....

### ISSUE THREAD

**Issue by ndsboy123** [TiniVi/safehax#38]
Hi guys
I wanted to homebrew my nintendo 2DS 11.1.0-34E.
I followed the 3ds.guide for my advice step by step.
Evrything worked well until I had to install boot9strap.
Section 1 worked, I could start "udsploit" at the first try.
But the next step isn´t working. When I start" safehax" I get the error  “PM INIT FAILED” .
I tried to use the "r19" release but I still get the issue. 
I am pretty sure that the guide was followed right and all the datas are in the right folders/positions.
I added the image in the post I hope you can see it. I would be really happy if you could help me.
Thank you !

![img_9651 1](https://user-images.githubusercontent.com/31374165/29744165-9067bfd0-8a9f-11e7-8219-9f646da0dc7f.JPG)

**Comment by TiniVi** [comment]
Your screenshot does not match your description as it seems as though the arm9 payload loaded.

**Comment by ndsboy123** [comment]
but I´m not able to get into the next step. I don´t  have a lot of knowledge in this stuff. 
So what should I do, where is my mistake ?

**Comment by TiniVi** [comment]
Please ask on a public forum or double check your files, it seems that safehax is not the issue here.
