### ISSUE TITLE
New 3ds 10.7 usa fails to load arm9 payload (SVCHAX)

### ISSUE THREAD

**Issue by FrozenChen** [TiniVi/safehax#4]
I used decrypt9 latest release as my arm9 payload(arm9.bin) and soundhax as my entry point. I first run svchax for the k11 privileges,upon going back to hb launcher i ran safehax which results on a black screen if arm9.bin is on sd root, otherwise it will say the missing payload message. Debugging didnt help since the text goes so fast it cant be read before the black screen. I lost count how many times i tried this prob 20+ times

**Comment by TiniVi** [comment]
The reason the text isn't useful is because it's meant to deal with crashes while the app is running. This crash is happening after application exit.

**Comment by TiniVi** [comment]
Same issue as #5, please reply to that issue.
